# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish Plugins to NPM

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  update-branches:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - run: echo 'test'
